use std::os::unix::fs::PermissionsExt;

use crate::settings::{DkimSettingsModel, RelaySettingsModel, SettingsModel, SmtpSettingsModel};

use super::*;

/// Headers which are covered by the dkim signature. Everything which is added by the
/// mail servers on the way (Received, Return-Path) must stay out of the list.
const DKIM_SIGNED_HEADERS: [&str; 6] = [
    "From",
    "To",
    "Subject",
    "Date",
    "MIME-Version",
    "Content-Type",
];

pub fn get_dkim_keys_directory(dkim: &DkimSettingsModel) -> String {
    format!("{}/{}", DKIM_KEYS_DIR, dkim.domain.trim())
}

pub fn get_dkim_private_key_file(dkim: &DkimSettingsModel) -> String {
    format!(
        "{}/{}.key",
        get_dkim_keys_directory(dkim),
        dkim.selector.trim()
    )
}

/// Compiles the kumod policy out of the settings model. kumod reads it on start up and
/// this is the only place where the settings turn into the mail server configuration.
pub fn compile_policy_lua(settings: &SettingsModel) -> String {
    let smtp = &settings.smtp;

    let mut result = String::new();

    result.push_str("-- Generated by my-smtp-sender out of the settings model.\n");
    result.push_str("-- Do not edit by hand - the file is rewritten on each start up.\n\n");
    result.push_str("local kumo = require 'kumo'\n\n");

    result.push_str(compile_dkim_keys_table(&settings.dkim).as_str());

    result.push_str("kumo.on('init', function()\n");
    result.push_str(
        format!(
            "  kumo.define_spool {{ name = 'data', path = '{}' }}\n",
            SPOOL_DATA_DIR
        )
        .as_str(),
    );
    result.push_str(
        format!(
            "  kumo.define_spool {{ name = 'meta', path = '{}' }}\n\n",
            SPOOL_META_DIR
        )
        .as_str(),
    );

    // The listener is bound to the loopback interface: the only client of it is this
    // service itself, so the mail server can never be used as an open relay.
    result.push_str("  kumo.start_esmtp_listener {\n");
    result.push_str(format!("    listen = '{}:{}',\n", LOCAL_SMTP_HOST, LOCAL_SMTP_PORT).as_str());
    result.push_str(
        format!(
            "    hostname = '{}',\n",
            escape_lua_string(smtp.my_hostname.trim())
        )
        .as_str(),
    );
    result.push_str(format!("    relay_hosts = {{ '{}', '::1' }},\n", LOCAL_SMTP_HOST).as_str());
    result.push_str(
        format!(
            "    max_message_size = {},\n",
            smtp.get_message_size_limit_bytes()
        )
        .as_str(),
    );
    result.push_str("  }\n\n");

    // Used by our own /api/mail-server/v1/status endpoint to read the state of the queues.
    result.push_str("  kumo.start_http_listener {\n");
    result.push_str(format!("    listen = '{}',\n", KUMO_HTTP_LISTENER).as_str());
    result.push_str(format!("    trusted_hosts = {{ '{}', '::1' }},\n", LOCAL_SMTP_HOST).as_str());
    result.push_str("  }\n\n");

    // Without a short segment duration the delivery records stay in the buffer of the mail
    // server for hours, and the log is empty exactly when it is needed - right after a
    // message failed to go out.
    result.push_str("  kumo.configure_local_logs {\n");
    result.push_str(format!("    log_dir = '{}',\n", LOG_DIR).as_str());
    result.push_str("    max_segment_duration = '10 seconds',\n");
    result.push_str("  }\n");
    result.push_str("end)\n\n");

    result.push_str(compile_message_received_handler(settings).as_str());

    result.push_str(compile_queue_config_handler(smtp).as_str());
    result.push_str(compile_egress_path_handler(smtp).as_str());

    result
}

fn compile_queue_config_handler(smtp: &SmtpSettingsModel) -> String {
    let mut result = String::new();

    // The real arity of the event is (domain, tenant, campaign, routing_domain).
    result.push_str(
        "kumo.on('get_queue_config', function(domain, tenant, campaign, routing_domain)\n",
    );
    result.push_str("  return kumo.make_queue_config {\n");
    result.push_str(
        format!(
            "    max_age = '{} hours',\n",
            smtp.get_max_queue_lifetime_hours()
        )
        .as_str(),
    );
    result.push_str("    retry_interval = '20 minutes',\n");
    result.push_str("    max_retry_interval = '2 hours',\n");
    // The relay is not configured here: the routing_domain of the message already replaces
    // the mx resolution, and it keeps the recipient domain in the name of the queue.
    result.push_str("  }\n");
    result.push_str("end)\n\n");

    result
}

fn compile_egress_path_handler(smtp: &SmtpSettingsModel) -> String {
    let ehlo_domain = escape_lua_string(smtp.my_hostname.trim());

    let mut result = String::new();

    // The real arity of the event is (routing_domain, egress_source, site_name). With the
    // relay the first argument is the host of the relay, which is how the credentials are
    // scoped to it and never sent anywhere else.
    result.push_str(
        "kumo.on('get_egress_path_config', function(routing_domain, egress_source, site_name)\n",
    );

    if let Some(relay) = &smtp.relay {
        let relay_host = escape_lua_string(relay.host.trim());

        result.push_str(
            format!(
                "  if routing_domain == '{}' or site_name == '{}' then\n",
                relay_host, relay_host
            )
            .as_str(),
        );
        result.push_str("    return kumo.make_egress_path {\n");
        result.push_str(format!("      ehlo_domain = '{}',\n", ehlo_domain).as_str());
        result.push_str(compile_relay_egress_path(relay).as_str());
        result.push_str("    }\n");
        result.push_str("  end\n\n");
    }

    result.push_str("  return kumo.make_egress_path {\n");
    result.push_str(format!("    ehlo_domain = '{}',\n", ehlo_domain).as_str());
    // Encrypted when the mail server of the recipient supports it, plain text when it does
    // not - the same behaviour any normal mail server has.
    result.push_str("    enable_tls = 'Opportunistic',\n");
    result.push_str("  }\n");
    result.push_str("end)\n");

    result
}

fn compile_relay_egress_path(relay: &RelaySettingsModel) -> String {
    let mut result = String::new();

    result.push_str(format!("      smtp_port = {},\n", relay.get_port()).as_str());
    // The relay is a known server which is reached over the internet - the credentials
    // must never travel in plain text. kumod refuses AUTH PLAIN without tls anyway.
    result.push_str("      enable_tls = 'Required',\n");
    // Both are about the mail server of the recipient, which is not who we are talking to.
    result.push_str("      enable_mta_sts = false,\n");
    result.push_str("      enable_dane = false,\n");

    if !relay.has_authentication() {
        return result;
    }

    if let Some(user) = relay.get_user() {
        result.push_str(
            format!(
                "      smtp_auth_plain_username = '{}',\n",
                escape_lua_string(user)
            )
            .as_str(),
        );
    }

    if let Some(password) = relay.get_password() {
        // A bare string here would be read as a PATH to a file with the password - an
        // inline value has to be wrapped into key_data.
        result.push_str(
            format!(
                "      smtp_auth_plain_password = {{ key_data = '{}' }},\n",
                escape_lua_string(password)
            )
            .as_str(),
        );
    }

    result
}

/// The policy carries the password of the relay, and the endpoints which show the policy
/// have no authentication - so whatever is handed out has the secrets taken out of it.
pub fn redact_policy_secrets(policy: &str) -> String {
    const SECRET_PREFIX: &str = "key_data = '";

    let mut result = String::new();

    for line in policy.lines() {
        match line.find(SECRET_PREFIX) {
            Some(index) => {
                result.push_str(&line[..index + SECRET_PREFIX.len()]);
                result.push_str("*** hidden ***' }");
            }
            None => result.push_str(line),
        }

        result.push('\n');
    }

    result
}

fn compile_dkim_keys_table(dkim_settings: &[DkimSettingsModel]) -> String {
    let mut result = String::new();

    result.push_str("local DKIM_KEYS = {\n");

    for dkim in dkim_settings {
        result.push_str(
            format!(
                "  ['{}'] = {{ selector = '{}', key = '{}' }},\n",
                escape_lua_string(dkim.domain.trim()),
                escape_lua_string(dkim.selector.trim()),
                escape_lua_string(get_dkim_private_key_file(dkim).as_str())
            )
            .as_str(),
        );
    }

    result.push_str("}\n\n");

    result
}

/// Everything which has to happen to a message the moment it is accepted: it is signed,
/// and - when a relay is configured - it is pointed at the relay instead of the mail
/// server of the recipient.
fn compile_message_received_handler(settings: &SettingsModel) -> String {
    let dkim_signing = compile_dkim_signing(&settings.dkim);
    let relay_routing = compile_relay_routing(settings.smtp.relay.as_ref());

    if dkim_signing.is_empty() && relay_routing.is_empty() {
        return String::new();
    }

    let mut result = String::new();

    result.push_str("kumo.on('smtp_server_message_received', function(msg)\n");
    result.push_str(dkim_signing.as_str());
    result.push_str(relay_routing.as_str());
    result.push_str("end)\n\n");

    result
}

fn compile_dkim_signing(dkim_settings: &[DkimSettingsModel]) -> String {
    if dkim_settings.is_empty() {
        return String::new();
    }

    let headers = DKIM_SIGNED_HEADERS
        .iter()
        .map(|header| format!("'{}'", header))
        .collect::<Vec<String>>()
        .join(", ");

    let mut result = String::new();

    // The domain of the From header is the one DMARC aligns the signature against - that
    // is why the key is picked by it and not by the envelope sender.
    result.push_str("  local from = msg:from_header()\n");
    result.push_str("  local dkim = nil\n\n");
    result.push_str("  if from ~= nil then\n");
    result.push_str("    dkim = DKIM_KEYS[from.domain]\n");
    result.push_str("  end\n\n");
    // No key for this domain - the mail still goes out, just unsigned.
    result.push_str("  if dkim ~= nil then\n");
    result.push_str("    msg:dkim_sign(kumo.dkim.rsa_sha256_signer {\n");
    result.push_str("      domain = from.domain,\n");
    result.push_str("      selector = dkim.selector,\n");
    result.push_str(format!("      headers = {{ {} }},\n", headers).as_str());
    result.push_str("      key = dkim.key,\n");
    result.push_str("    })\n");
    result.push_str("  end\n\n");

    result
}

/// The documented way to hand everything over to one smart host: the routing domain of the
/// message replaces the mx resolution, while the recipient domain stays in the name of the
/// queue - so the retries and the statistics are still per recipient domain.
fn compile_relay_routing(relay: Option<&RelaySettingsModel>) -> String {
    let Some(relay) = relay else {
        return String::new();
    };

    format!(
        "  msg:set_meta('routing_domain', '{}')\n",
        escape_lua_string(relay.host.trim())
    )
}

/// Writes everything kumod needs: the directories, the dkim keys and the policy itself.
pub async fn write_kumo_mta_config(settings: &SettingsModel) -> Result<(), String> {
    create_directory(POLICY_DIR).await?;
    create_directory(DKIM_KEYS_DIR).await?;
    create_directory(SPOOL_DATA_DIR).await?;
    create_directory(SPOOL_META_DIR).await?;
    create_directory(LOG_DIR).await?;

    for dkim in settings.dkim.iter() {
        copy_dkim_private_key(dkim).await?;
    }

    write_file(POLICY_FILE, compile_policy_lua(settings).as_str()).await?;

    // kumod drops its privileges to the kumod user, our service is running as root -
    // everything kumod has to read or write has to belong to it.
    for path in [DKIM_KEYS_DIR, SPOOL_DATA_DIR, SPOOL_META_DIR, LOG_DIR] {
        change_owner_to_kumod(path).await?;
    }

    Ok(())
}

/// The key file belongs to whoever mounted it into the container - it is copied into the
/// own directory of the mail server instead of being touched in place, because kumod reads
/// it after it has dropped its privileges to the kumod user, and changing the owner of a
/// bind mounted file would change it on the host as well.
async fn copy_dkim_private_key(dkim: &DkimSettingsModel) -> Result<(), String> {
    let source_file = dkim.get_private_key_path();

    let private_key = read_or_generate_dkim_private_key(dkim, source_file.as_str()).await?;

    create_directory(get_dkim_keys_directory(dkim).as_str()).await?;

    let destination_file = get_dkim_private_key_file(dkim);

    let mut private_key = private_key.trim().to_string();
    private_key.push('\n');

    write_file(destination_file.as_str(), private_key.as_str()).await?;

    if let Err(err) = tokio::fs::set_permissions(
        destination_file.as_str(),
        std::fs::Permissions::from_mode(0o600),
    )
    .await
    {
        return Err(format!(
            "Can not set permissions of the file '{}'. Err: {}",
            destination_file, err
        ));
    }

    Ok(())
}

/// A file which is not there yet, or which is there but empty - `touch key.pem` before the
/// first start, so that docker mounts a file and not a directory - means "generate it for
/// me": the key is created and written back to the very path the settings point at, so the
/// next start finds it and nothing is regenerated.
async fn read_or_generate_dkim_private_key(
    dkim: &DkimSettingsModel,
    source_file: &str,
) -> Result<String, String> {
    match tokio::fs::read_to_string(source_file).await {
        Ok(private_key) => {
            if !private_key.trim().is_empty() {
                return Ok(private_key);
            }
        }
        Err(err) => {
            if err.kind() != std::io::ErrorKind::NotFound {
                return Err(format!(
                    "Can not read the dkim private key of the domain '{}' from the file '{}'. Err: {}",
                    dkim.domain, source_file, err
                ));
            }
        }
    }

    let private_key = crate::scripts::generate_dkim_private_key().await?;

    if let Some((directory, _)) = source_file.rsplit_once('/') {
        create_directory(directory).await?;
    }

    if let Err(err) = tokio::fs::write(source_file, private_key.as_str()).await {
        return Err(format!(
            "The dkim private key of the domain '{}' has to be generated, but the file '{}' can not be written. Is the directory mounted read only? Err: {}",
            dkim.domain, source_file, err
        ));
    }

    if let Err(err) =
        tokio::fs::set_permissions(source_file, std::fs::Permissions::from_mode(0o600)).await
    {
        return Err(format!(
            "Can not set permissions of the file '{}'. Err: {}",
            source_file, err
        ));
    }

    report_generated_dkim_key(dkim, source_file, private_key.as_str());

    Ok(private_key)
}

/// A key nobody published in dns is worse than no key at all: the mail goes out signed and
/// every recipient fails to verify it. So the record to publish is printed as loudly as the
/// service can print it.
fn report_generated_dkim_key(dkim: &DkimSettingsModel, source_file: &str, private_key: &str) {
    let record = match crate::scripts::compile_dkim_dns_record(
        &dkim.domain,
        &dkim.selector,
        private_key,
    ) {
        Ok(record) => record,
        Err(err) => {
            my_logger::LOGGER.write_error(
                    "read_or_generate_dkim_private_key",
                    format!(
                        "The dkim key of the domain '{}' is generated, but its dns record can not be compiled. Err: {}",
                        dkim.domain, err
                    ),
                    my_logger::LogEventCtx::new(),
                );
            return;
        }
    };

    println!("--------------------------------------------------------------------------");
    println!(
        "A new dkim key of the domain '{}' is generated into '{}'.",
        dkim.domain, source_file
    );
    println!("Publish this dns record, otherwise the signature can not be verified:");
    println!("  name:  {}", record.name);
    println!("  type:  TXT");
    println!("  value: {}", record.value);
    println!("--------------------------------------------------------------------------");

    my_logger::LOGGER.write_warning(
        "read_or_generate_dkim_private_key",
        format!(
            "A new dkim key is generated for the domain '{}'. Until the TXT record '{}' is published, the mail is signed with a key which can not be verified",
            dkim.domain, record.name
        ),
        my_logger::LogEventCtx::new(),
    );
}

async fn change_owner_to_kumod(path: &str) -> Result<(), String> {
    let args = vec![
        "-R".to_string(),
        format!("{}:{}", KUMOD_USER, KUMOD_USER),
        path.to_string(),
    ];

    let result = execute_os_command("chown", &args).await?;

    if !result.is_success() {
        return Err(format!(
            "Can not change the owner of '{}' to {}. {}",
            path,
            KUMOD_USER,
            result.get_output()
        ));
    }

    Ok(())
}

async fn create_directory(path: &str) -> Result<(), String> {
    if let Err(err) = tokio::fs::create_dir_all(path).await {
        return Err(format!(
            "Can not create the directory '{}'. Err: {}",
            path, err
        ));
    }

    Ok(())
}

async fn write_file(path: &str, content: &str) -> Result<(), String> {
    if let Err(err) = tokio::fs::write(path, content).await {
        return Err(format!("Can not write the file '{}'. Err: {}", path, err));
    }

    Ok(())
}

/// The values are coming from the settings and end up inside the lua single quoted
/// string literals.
fn escape_lua_string(src: &str) -> String {
    src.replace('\\', "\\\\").replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use crate::settings::{
        DkimSettingsModel, RelaySettingsModel, SettingsModel, SmtpSettingsModel,
    };

    use super::{compile_policy_lua, escape_lua_string};

    fn create_test_settings(with_dkim: bool) -> SettingsModel {
        SettingsModel {
            smtp: SmtpSettingsModel {
                my_hostname: "mail.mydomain.com".to_string(),
                default_from_email: "no-reply@mydomain.com".to_string(),
                default_from_name: Some("My Service".to_string()),
                message_size_limit_mb: Some(25),
                max_queue_lifetime_hours: Some(24),
                relay: None,
            },
            dkim: if with_dkim {
                vec![DkimSettingsModel {
                    domain: "mydomain.com".to_string(),
                    selector: "mail".to_string(),
                    private_key_path: "/etc/my-smtp-sender/dkim/mydomain.com.key".to_string(),
                }]
            } else {
                vec![]
            },
        }
    }

    #[test]
    fn test_lua_string_is_escaped() {
        assert_eq!(escape_lua_string("my'domain").as_str(), "my\\'domain");
        assert_eq!(escape_lua_string("my\\domain").as_str(), "my\\\\domain");
    }

    #[test]
    fn test_policy_has_everything_kumod_needs() {
        let policy = compile_policy_lua(&create_test_settings(true));

        println!("{}", policy);

        assert!(policy.contains("kumo.define_spool { name = 'data'"));
        assert!(policy.contains("max_segment_duration = '10 seconds'"));
        assert!(policy.contains("kumo.start_esmtp_listener"));
        assert!(policy.contains("listen = '127.0.0.1:25'"));
        assert!(policy.contains("hostname = 'mail.mydomain.com'"));
        assert!(policy.contains("max_message_size = 26214400"));
        assert!(policy.contains("max_age = '24 hours'"));
        assert!(policy.contains("msg:dkim_sign"));
        assert!(policy.contains("['mydomain.com'] = { selector = 'mail'"));
    }

    #[test]
    fn test_policy_with_relay_routes_everything_to_it() {
        let mut settings = create_test_settings(false);

        settings.smtp.relay = Some(RelaySettingsModel {
            host: "smtp.mailgun.org".to_string(),
            port: Some(587),
            user: Some("postmaster@mydomain.com".to_string()),
            password: Some("secret".to_string()),
        });

        let policy = compile_policy_lua(&settings);

        // The relay is applied by pointing the message at it, not by an mx_list - the
        // protocol block of the queue config is exactly what kumod refused to parse.
        assert!(policy.contains("msg:set_meta('routing_domain', 'smtp.mailgun.org')"));
        assert!(!policy.contains("mx_list"));
        assert!(!policy.contains("protocol"));
        assert!(policy.contains("if routing_domain == 'smtp.mailgun.org'"));
        assert!(policy.contains("smtp_port = 587"));
        assert!(policy.contains("enable_tls = 'Required'"));
        assert!(policy.contains("smtp_auth_plain_username = 'postmaster@mydomain.com'"));
        assert!(policy.contains("smtp_auth_plain_password = { key_data = 'secret' }"));
    }

    #[test]
    fn test_policy_without_relay_delivers_directly() {
        let policy = compile_policy_lua(&create_test_settings(false));

        assert!(!policy.contains("routing_domain', '"));
        assert!(policy.contains("enable_tls = 'Opportunistic'"));
        assert!(policy.contains("kumo.make_egress_path {"));
    }

    #[test]
    fn test_policy_without_dkim_does_not_sign() {
        let policy = compile_policy_lua(&create_test_settings(false));

        assert!(!policy.contains("dkim_sign"));
        assert!(policy.contains("kumo.start_esmtp_listener"));
    }
}
