use std::os::unix::fs::PermissionsExt;

use crate::settings::{DkimSettingsModel, RelaySettingsModel, SettingsModel, SmtpSettingsModel};

use super::*;

/// Headers which are covered by the dkim signature. Everything which is added by the
/// mail servers on the way (Received, Return-Path) must stay out of the list.
const DKIM_SIGNED_HEADERS: [&str; 6] = [
    "From",
    "To",
    "Subject",
    "Date",
    "MIME-Version",
    "Content-Type",
];

pub fn get_dkim_keys_directory(dkim: &DkimSettingsModel) -> String {
    format!("{}/{}", DKIM_KEYS_DIR, dkim.domain.trim())
}

pub fn get_dkim_private_key_file(dkim: &DkimSettingsModel) -> String {
    format!(
        "{}/{}.key",
        get_dkim_keys_directory(dkim),
        dkim.selector.trim()
    )
}

/// Compiles the kumod policy out of the settings model. kumod reads it on start up and
/// this is the only place where the settings turn into the mail server configuration.
pub fn compile_policy_lua(settings: &SettingsModel) -> String {
    let smtp = &settings.smtp;

    let mut result = String::new();

    result.push_str("-- Generated by my-smtp-sender out of the settings model.\n");
    result.push_str("-- Do not edit by hand - the file is rewritten on each start up.\n\n");
    result.push_str("local kumo = require 'kumo'\n\n");

    result.push_str(compile_dkim_keys_table(&settings.dkim).as_str());

    result.push_str("kumo.on('init', function()\n");
    result.push_str(
        format!(
            "  kumo.define_spool {{ name = 'data', path = '{}' }}\n",
            SPOOL_DATA_DIR
        )
        .as_str(),
    );
    result.push_str(
        format!(
            "  kumo.define_spool {{ name = 'meta', path = '{}' }}\n\n",
            SPOOL_META_DIR
        )
        .as_str(),
    );

    // The listener is bound to the loopback interface: the only client of it is this
    // service itself, so the mail server can never be used as an open relay.
    result.push_str("  kumo.start_esmtp_listener {\n");
    result.push_str(format!("    listen = '{}:{}',\n", LOCAL_SMTP_HOST, LOCAL_SMTP_PORT).as_str());
    result.push_str(
        format!(
            "    hostname = '{}',\n",
            escape_lua_string(smtp.my_hostname.trim())
        )
        .as_str(),
    );
    result.push_str(format!("    relay_hosts = {{ '{}', '::1' }},\n", LOCAL_SMTP_HOST).as_str());
    result.push_str(
        format!(
            "    max_message_size = {},\n",
            smtp.get_message_size_limit_bytes()
        )
        .as_str(),
    );
    result.push_str("  }\n\n");

    // Used by our own /api/mail-server/v1/status endpoint to read the state of the queues.
    result.push_str("  kumo.start_http_listener {\n");
    result.push_str(format!("    listen = '{}',\n", KUMO_HTTP_LISTENER).as_str());
    result.push_str(format!("    trusted_hosts = {{ '{}', '::1' }},\n", LOCAL_SMTP_HOST).as_str());
    result.push_str("  }\n\n");

    result.push_str(
        format!(
            "  kumo.configure_local_logs {{ log_dir = '{}' }}\n",
            LOG_DIR
        )
        .as_str(),
    );
    result.push_str("end)\n\n");

    result.push_str(compile_dkim_signing_handler(&settings.dkim).as_str());

    result.push_str(compile_queue_config_handler(smtp).as_str());
    result.push_str(compile_egress_path_handler(smtp).as_str());

    result
}

fn compile_queue_config_handler(smtp: &SmtpSettingsModel) -> String {
    let mut result = String::new();

    result.push_str(
        "kumo.on('get_queue_config', function(domain, tenant, campaign, routing_domain)\n",
    );
    result.push_str("  return kumo.make_queue_config {\n");
    result.push_str(
        format!(
            "    max_age = '{} hours',\n",
            smtp.get_max_queue_lifetime_hours()
        )
        .as_str(),
    );
    result.push_str("    retry_interval = '20 minutes',\n");
    result.push_str("    max_retry_interval = '2 hours',\n");

    if let Some(relay) = &smtp.relay {
        // Everything goes to the relay instead of the mail server of the recipient.
        result.push_str("    protocol = {\n");
        result.push_str("      smtp_client = {\n");
        result.push_str(
            format!(
                "        mx_list = {{ '{}' }},\n",
                escape_lua_string(relay.host.trim())
            )
            .as_str(),
        );
        result.push_str("      },\n");
        result.push_str("    },\n");
    }

    result.push_str("  }\n");
    result.push_str("end)\n\n");

    result
}

fn compile_egress_path_handler(smtp: &SmtpSettingsModel) -> String {
    let mut result = String::new();

    result.push_str(
        "kumo.on('get_egress_path_config', function(routing_domain, egress_source, site_name)\n",
    );
    result.push_str("  return kumo.make_egress_path {\n");
    result.push_str(
        format!(
            "    ehlo_domain = '{}',\n",
            escape_lua_string(smtp.my_hostname.trim())
        )
        .as_str(),
    );

    match &smtp.relay {
        Some(relay) => result.push_str(compile_relay_egress_path(relay).as_str()),
        None => {
            // Encrypted when the mail server of the recipient supports it, plain text when
            // it does not - the same behaviour any normal mail server has.
            result.push_str("    enable_tls = 'Opportunistic',\n");
        }
    }

    result.push_str("  }\n");
    result.push_str("end)\n");

    result
}

fn compile_relay_egress_path(relay: &RelaySettingsModel) -> String {
    let mut result = String::new();

    result.push_str(format!("    smtp_port = {},\n", relay.get_port()).as_str());
    // The relay is a known server which is reached over the internet - the credentials
    // must never travel in plain text.
    result.push_str("    enable_tls = 'Required',\n");

    if !relay.has_authentication() {
        return result;
    }

    if let Some(user) = relay.get_user() {
        result.push_str(
            format!(
                "    smtp_auth_plain_username = '{}',\n",
                escape_lua_string(user)
            )
            .as_str(),
        );
    }

    if let Some(password) = relay.get_password() {
        result.push_str(
            format!(
                "    smtp_auth_plain_password = {{ key_data = '{}' }},\n",
                escape_lua_string(password)
            )
            .as_str(),
        );
    }

    result
}

fn compile_dkim_keys_table(dkim_settings: &[DkimSettingsModel]) -> String {
    let mut result = String::new();

    result.push_str("local DKIM_KEYS = {\n");

    for dkim in dkim_settings {
        result.push_str(
            format!(
                "  ['{}'] = {{ selector = '{}', key = '{}' }},\n",
                escape_lua_string(dkim.domain.trim()),
                escape_lua_string(dkim.selector.trim()),
                escape_lua_string(get_dkim_private_key_file(dkim).as_str())
            )
            .as_str(),
        );
    }

    result.push_str("}\n\n");

    result
}

fn compile_dkim_signing_handler(dkim_settings: &[DkimSettingsModel]) -> String {
    if dkim_settings.is_empty() {
        return String::new();
    }

    let headers = DKIM_SIGNED_HEADERS
        .iter()
        .map(|header| format!("'{}'", header))
        .collect::<Vec<String>>()
        .join(", ");

    let mut result = String::new();

    result.push_str("kumo.on('smtp_server_message_received', function(msg)\n");
    // The domain of the From header is the one DMARC aligns the signature against - that
    // is why the key is picked by it and not by the envelope sender.
    result.push_str("  local from = msg:from_header()\n");
    result.push_str("  if from == nil then\n");
    result.push_str("    return\n");
    result.push_str("  end\n\n");
    result.push_str("  local dkim = DKIM_KEYS[from.domain]\n");
    result.push_str("  if dkim == nil then\n");
    // No key for this domain - the mail still goes out, just unsigned.
    result.push_str("    return\n");
    result.push_str("  end\n\n");
    result.push_str("  msg:dkim_sign(kumo.dkim.rsa_sha256_signer {\n");
    result.push_str("    domain = from.domain,\n");
    result.push_str("    selector = dkim.selector,\n");
    result.push_str(format!("    headers = {{ {} }},\n", headers).as_str());
    result.push_str("    key = dkim.key,\n");
    result.push_str("  })\n");
    result.push_str("end)\n\n");

    result
}

/// Writes everything kumod needs: the directories, the dkim keys and the policy itself.
pub async fn write_kumo_mta_config(settings: &SettingsModel) -> Result<(), String> {
    create_directory(POLICY_DIR).await?;
    create_directory(DKIM_KEYS_DIR).await?;
    create_directory(SPOOL_DATA_DIR).await?;
    create_directory(SPOOL_META_DIR).await?;
    create_directory(LOG_DIR).await?;

    for dkim in settings.dkim.iter() {
        copy_dkim_private_key(dkim).await?;
    }

    write_file(POLICY_FILE, compile_policy_lua(settings).as_str()).await?;

    // kumod drops its privileges to the kumod user, our service is running as root -
    // everything kumod has to read or write has to belong to it.
    for path in [DKIM_KEYS_DIR, SPOOL_DATA_DIR, SPOOL_META_DIR, LOG_DIR] {
        change_owner_to_kumod(path).await?;
    }

    Ok(())
}

/// The key file belongs to whoever mounted it into the container - it is copied into the
/// own directory of the mail server instead of being touched in place, because kumod reads
/// it after it has dropped its privileges to the kumod user, and changing the owner of a
/// bind mounted file would change it on the host as well.
async fn copy_dkim_private_key(dkim: &DkimSettingsModel) -> Result<(), String> {
    let source_file = dkim.get_private_key_path();

    let private_key = match tokio::fs::read_to_string(source_file.as_str()).await {
        Ok(private_key) => private_key,
        Err(err) => {
            return Err(format!(
                "Can not read the dkim private key of the domain '{}' from the file '{}'. Err: {}",
                dkim.domain, source_file, err
            ));
        }
    };

    if private_key.trim().is_empty() {
        return Err(format!(
            "The dkim private key file '{}' of the domain '{}' is empty",
            source_file, dkim.domain
        ));
    }

    create_directory(get_dkim_keys_directory(dkim).as_str()).await?;

    let destination_file = get_dkim_private_key_file(dkim);

    let mut private_key = private_key.trim().to_string();
    private_key.push('\n');

    write_file(destination_file.as_str(), private_key.as_str()).await?;

    if let Err(err) = tokio::fs::set_permissions(
        destination_file.as_str(),
        std::fs::Permissions::from_mode(0o600),
    )
    .await
    {
        return Err(format!(
            "Can not set permissions of the file '{}'. Err: {}",
            destination_file, err
        ));
    }

    Ok(())
}

async fn change_owner_to_kumod(path: &str) -> Result<(), String> {
    let args = vec![
        "-R".to_string(),
        format!("{}:{}", KUMOD_USER, KUMOD_USER),
        path.to_string(),
    ];

    let result = execute_os_command("chown", &args).await?;

    if !result.is_success() {
        return Err(format!(
            "Can not change the owner of '{}' to {}. {}",
            path,
            KUMOD_USER,
            result.get_output()
        ));
    }

    Ok(())
}

async fn create_directory(path: &str) -> Result<(), String> {
    if let Err(err) = tokio::fs::create_dir_all(path).await {
        return Err(format!(
            "Can not create the directory '{}'. Err: {}",
            path, err
        ));
    }

    Ok(())
}

async fn write_file(path: &str, content: &str) -> Result<(), String> {
    if let Err(err) = tokio::fs::write(path, content).await {
        return Err(format!("Can not write the file '{}'. Err: {}", path, err));
    }

    Ok(())
}

/// The values are coming from the settings and end up inside the lua single quoted
/// string literals.
fn escape_lua_string(src: &str) -> String {
    src.replace('\\', "\\\\").replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use crate::settings::{
        DkimSettingsModel, RelaySettingsModel, SettingsModel, SmtpSettingsModel,
    };

    use super::{compile_policy_lua, escape_lua_string};

    fn create_test_settings(with_dkim: bool) -> SettingsModel {
        SettingsModel {
            smtp: SmtpSettingsModel {
                my_hostname: "mail.mydomain.com".to_string(),
                default_from_email: "no-reply@mydomain.com".to_string(),
                default_from_name: Some("My Service".to_string()),
                message_size_limit_mb: Some(25),
                max_queue_lifetime_hours: Some(24),
                relay: None,
            },
            dkim: if with_dkim {
                vec![DkimSettingsModel {
                    domain: "mydomain.com".to_string(),
                    selector: "mail".to_string(),
                    private_key_path: "/etc/my-smtp-sender/dkim/mydomain.com.key".to_string(),
                }]
            } else {
                vec![]
            },
        }
    }

    #[test]
    fn test_lua_string_is_escaped() {
        assert_eq!(escape_lua_string("my'domain").as_str(), "my\\'domain");
        assert_eq!(escape_lua_string("my\\domain").as_str(), "my\\\\domain");
    }

    #[test]
    fn test_policy_has_everything_kumod_needs() {
        let policy = compile_policy_lua(&create_test_settings(true));

        println!("{}", policy);

        assert!(policy.contains("kumo.define_spool { name = 'data'"));
        assert!(policy.contains("kumo.start_esmtp_listener"));
        assert!(policy.contains("listen = '127.0.0.1:25'"));
        assert!(policy.contains("hostname = 'mail.mydomain.com'"));
        assert!(policy.contains("max_message_size = 26214400"));
        assert!(policy.contains("max_age = '24 hours'"));
        assert!(policy.contains("msg:dkim_sign"));
        assert!(policy.contains("['mydomain.com'] = { selector = 'mail'"));
    }

    #[test]
    fn test_policy_with_relay_routes_everything_to_it() {
        let mut settings = create_test_settings(false);

        settings.smtp.relay = Some(RelaySettingsModel {
            host: "smtp.mailgun.org".to_string(),
            port: Some(587),
            user: Some("postmaster@mydomain.com".to_string()),
            password: Some("secret".to_string()),
        });

        let policy = compile_policy_lua(&settings);

        assert!(policy.contains("mx_list = { 'smtp.mailgun.org' }"));
        assert!(policy.contains("smtp_port = 587"));
        assert!(policy.contains("enable_tls = 'Required'"));
        assert!(policy.contains("smtp_auth_plain_username = 'postmaster@mydomain.com'"));
        assert!(policy.contains("smtp_auth_plain_password = { key_data = 'secret' }"));
    }

    #[test]
    fn test_policy_without_relay_delivers_directly() {
        let policy = compile_policy_lua(&create_test_settings(false));

        assert!(!policy.contains("mx_list"));
        assert!(policy.contains("enable_tls = 'Opportunistic'"));
        assert!(policy.contains("kumo.make_egress_path {"));
    }

    #[test]
    fn test_policy_without_dkim_does_not_sign() {
        let policy = compile_policy_lua(&create_test_settings(false));

        assert!(!policy.contains("dkim_sign"));
        assert!(policy.contains("kumo.start_esmtp_listener"));
    }
}
